import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { Providers } from '@/providers'
import { AuthWrapper } from '@/providers/auth-provider/auth.wrapper'
import { DataProviderWrapper } from '@/providers/data-provider/data-provider.wrapper'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})
const mermaid = localFont({
  src: './fonts/MermaidSwashCaps.woff',
  variable: '--font-mermaid',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mermaid.variable} antialiased`}
      >
        <Toaster position='top-center' />
        <Providers>
          <DataProviderWrapper>
            <AuthWrapper>{children}</AuthWrapper>
          </DataProviderWrapper>
        </Providers>
      </body>
    </html>
  )
}
